file:
  upload-dir: ./uploads
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:file:./data/demo
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: udqhynnyocxsixgr
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: amilanaotunna93@gmail.com
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 215MB
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file:
    name: /logs/application-debug.log
management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: 8080
  servlet:
    context-path: /fileUploadMS